#! /bin/bash
PASSWORD=$1
cp back_up ~/
echo "* 0 * * * /bin/bash back_up ${PASSWORD}"> backup_file
echo "* * * * * grep /var/log/nginx/access.log > /var/www/linux.com/log" >> backup_file
crontab -u $USER backup_file

